-- INSERTING 60 AUTHORS (Sample)
INSERT INTO author (id, first_name, last_name, email, bio, genere) VALUES
                                                                       (1, 'Liam', 'Anderson', 'liam.anderson@example.com', 'Award-winning novelist known for character-driven storytelling.', 'Fiction'),
                                                                       (2, 'Olivia', 'Brown', 'olivia.brown@example.com', 'Writes heartfelt stories exploring relationships and identity.', 'Romance'),
                                                                       (3, 'Noah', 'Clark', 'noah.clark@example.com', 'Tech enthusiast blending science with imaginative narratives.', 'Science Fiction'),
                                                                       (4, 'Emma', 'Davis', 'emma.davis@example.com', 'Focuses on emotional journeys and human resilience.', 'Drama'),
                                                                       (5, 'Oliver', 'Evans', 'oliver.evans@example.com', 'Fantasy author inspired by mythology and folklore.', 'Fantasy'),

                                                                       (6, 'Ava', 'Foster', 'ava.foster@example.com', 'Writes fast-paced thrillers with strong female leads.', 'Thriller'),
                                                                       (7, 'Elijah', 'Green', 'elijah.green@example.com', 'Explores nature, survival, and adventure through fiction.', 'Adventure'),
                                                                       (8, 'Sophia', 'Harris', 'sophia.harris@example.com', 'Poetic storyteller with a love for historical settings.', 'Historical Fiction'),
                                                                       (9, 'William', 'Irwin', 'william.irwin@example.com', 'Blends mystery with psychological depth.', 'Mystery'),
                                                                       (10, 'Isabella', 'Jackson', 'isabella.jackson@example.com', 'Romantic novelist focusing on modern relationships.', 'Romance'),

                                                                       (11, 'James', 'King', 'james.king@example.com', 'Writes political thrillers inspired by real-world events.', 'Thriller'),
                                                                       (12, 'Mia', 'Lewis', 'mia.lewis@example.com', 'Creates uplifting stories centered on personal growth.', 'Self-Help'),
                                                                       (13, 'Benjamin', 'Martin', 'benjamin.martin@example.com', 'Science fiction writer fascinated by AI and future societies.', 'Science Fiction'),
                                                                       (14, 'Charlotte', 'Nelson', 'charlotte.nelson@example.com', 'Fantasy author crafting rich worlds and epic quests.', 'Fantasy'),
                                                                       (15, 'Lucas', 'Owens', 'lucas.owens@example.com', 'Adventure writer with a background in travel journalism.', 'Adventure'),

                                                                       (16, 'Amelia', 'Parker', 'amelia.parker@example.com', 'Writes emotional dramas with strong family themes.', 'Drama'),
                                                                       (17, 'Henry', 'Quinn', 'henry.quinn@example.com', 'Crime novelist known for gritty urban settings.', 'Crime'),
                                                                       (18, 'Evelyn', 'Roberts', 'evelyn.roberts@example.com', 'Focuses on inspirational stories and life lessons.', 'Inspirational'),
                                                                       (19, 'Alexander', 'Scott', 'alexander.scott@example.com', 'Historical fiction author with academic research roots.', 'Historical Fiction'),
                                                                       (20, 'Harper', 'Turner', 'harper.turner@example.com', 'Writes contemporary fiction with social commentary.', 'Fiction'),

                                                                       (21, 'Daniel', 'Underwood', 'daniel.underwood@example.com', 'Cyberpunk writer exploring technology and ethics.', 'Science Fiction'),
                                                                       (22, 'Ella', 'Vasquez', 'ella.vasquez@example.com', 'Romantic suspense author with international settings.', 'Romantic Suspense'),
                                                                       (23, 'Matthew', 'Walker', 'matthew.walker@example.com', 'Non-fiction writer covering leadership and productivity.', 'Non-Fiction'),
                                                                       (24, 'Abigail', 'Xu', 'abigail.xu@example.com', 'Writes cross-cultural stories rooted in personal experiences.', 'Literary Fiction'),
                                                                       (25, 'Joseph', 'Young', 'joseph.young@example.com', 'Fantasy and mythological storyteller.', 'Fantasy'),

                                                                       (26, 'Emily', 'Zimmerman', 'emily.zimmerman@example.com', 'Children’s author creating imaginative worlds.', 'Children'),
                                                                       (27, 'Samuel', 'Adams', 'samuel.adams@example.com', 'Writes political and historical non-fiction.', 'History'),
                                                                       (28, 'Grace', 'Bennett', 'grace.bennett@example.com', 'Lifestyle writer focusing on mindfulness and wellness.', 'Wellness'),
                                                                       (29, 'David', 'Carter', 'david.carter@example.com', 'Action-packed thrillers with military themes.', 'Action'),
                                                                       (30, 'Chloe', 'Diaz', 'chloe.diaz@example.com', 'Writes coming-of-age stories with emotional depth.', 'Young Adult'),

                                                                       (31, 'Andrew', 'Edwards', 'andrew.edwards@example.com', 'Mystery writer inspired by classic detective novels.', 'Mystery'),
                                                                       (32, 'Lily', 'Fisher', 'lily.fisher@example.com', 'Writes cozy fiction set in small towns.', 'Cozy Fiction'),
                                                                       (33, 'Joshua', 'Gomez', 'joshua.gomez@example.com', 'Tech blogger turned non-fiction author.', 'Technology'),
                                                                       (34, 'Hannah', 'Howard', 'hannah.howard@example.com', 'Writes heartfelt romance novels.', 'Romance'),
                                                                       (35, 'Ryan', 'Ingram', 'ryan.ingram@example.com', 'Explores dystopian futures and social structures.', 'Dystopian'),

                                                                       (36, 'Victoria', 'Jones', 'victoria.jones@example.com', 'Historical romance writer.', 'Historical Romance'),
                                                                       (37, 'Nathan', 'Keller', 'nathan.keller@example.com', 'Writes dark psychological thrillers.', 'Psychological Thriller'),
                                                                       (38, 'Zoe', 'Lopez', 'zoe.lopez@example.com', 'Creative non-fiction storyteller.', 'Creative Non-Fiction'),
                                                                       (39, 'Christopher', 'Morris', 'christopher.morris@example.com', 'Writes epic fantasy sagas.', 'Fantasy'),
                                                                       (40, 'Natalie', 'Nguyen', 'natalie.nguyen@example.com', 'Cultural essays and modern fiction writer.', 'Literary Fiction'),

                                                                       (41, 'Aaron', 'Ortiz', 'aaron.ortiz@example.com', 'Crime fiction author with investigative background.', 'Crime'),
                                                                       (42, 'Sofia', 'Patel', 'sofia.patel@example.com', 'Writes inspirational biographies.', 'Biography'),
                                                                       (43, 'Jonathan', 'Reed', 'jonathan.reed@example.com', 'Science-based non-fiction author.', 'Science'),
                                                                       (44, 'Claire', 'Stewart', 'claire.stewart@example.com', 'Writes emotional family dramas.', 'Drama'),
                                                                       (45, 'Thomas', 'Taylor', 'thomas.taylor@example.com', 'Political and economic analyst turned author.', 'Economics'),

                                                                       (46, 'Lucy', 'Wilson', 'lucy.wilson@example.com', 'Writes light-hearted romantic comedies.', 'Romantic Comedy'),
                                                                       (47, 'Ethan', 'Moore', 'ethan.moore@example.com', 'Explores survival stories and human endurance.', 'Adventure'),
                                                                       (48, 'Natalia', 'Petrov', 'natalia.petrov@example.com', 'Writes historical novels set in Eastern Europe.', 'Historical Fiction'),
                                                                       (49, 'Michael', 'Brooks', 'michael.brooks@example.com', 'Focuses on leadership and career growth.', 'Business'),
                                                                       (50, 'Sarah', 'Coleman', 'sarah.coleman@example.com', 'Writes emotional young adult fiction.', 'Young Adult'),

                                                                       (51, 'Daniel', 'Price', 'daniel.price@example.com', 'Tech-driven thrillers blending reality and fiction.', 'Tech Thriller'),
                                                                       (52, 'Priya', 'Sharma', 'priya.sharma@example.com', 'Writes cultural and social commentary.', 'Essays'),
                                                                       (53, 'Leo', 'Romano', 'leo.romano@example.com', 'Crime and mafia fiction author.', 'Crime'),
                                                                       (54, 'Anna', 'Kowalski', 'anna.kowalski@example.com', 'Writes war-time historical fiction.', 'Historical Fiction'),
                                                                       (55, 'Mark', 'Peterson', 'mark.peterson@example.com', 'Outdoor adventure and travel writing.', 'Travel'),

                                                                       (56, 'Nina', 'Ivanova', 'nina.ivanova@example.com', 'Psychological fiction with deep character studies.', 'Psychological Fiction'),
                                                                       (57, 'Paul', 'Henderson', 'paul.henderson@example.com', 'Writes classic-style detective novels.', 'Detective'),
                                                                       (58, 'Irene', 'Mendez', 'irene.mendez@example.com', 'Writes poetry and short literary fiction.', 'Poetry'),
                                                                       (59, 'Kevin', 'OConnor', 'kevin.oconnor@example.com', 'Military history and war analysis.', 'Military History'),
                                                                       (60, 'Monica', 'Rossi', 'monica.rossi@example.com', 'Romantic fiction inspired by European settings.', 'Romance');

-- INSERTING 100 BOOKS (Distributed)
INSERT INTO book (id, title, genere, author_id) VALUES
                                                    (1, 'The Great Beyond', 'Fiction', 1),
                                                    (2, 'Echoes of Tomorrow', 'Science Fiction', 3),
                                                    (3, 'Shadows of Time', 'Drama', 4),
                                                    (4, 'Whispers in the Wind', 'Romance', 2),
                                                    (5, 'Code of Destiny', 'Science Fiction', 13),

                                                    (6, 'Falling Stars', 'Drama', 16),
                                                    (7, 'Beyond the Horizon', 'Adventure', 7),
                                                    (8, 'Hidden Truths', 'Thriller', 6),
                                                    (9, 'Garden of Secrets', 'Historical Fiction', 8),
                                                    (10, 'Iron Kingdom', 'Fantasy', 9),

                                                    (11, 'The Long Journey Home', 'Fiction', 10),
                                                    (12, 'Midnight Signals', 'Thriller', 11),
                                                    (13, 'Fragments of Us', 'Romance', 12),
                                                    (14, 'Empire of Sand', 'Fantasy', 14),
                                                    (15, 'Northern Lights', 'Adventure', 15),

                                                    (16, 'The Forgotten Shore', 'Drama', 16),
                                                    (17, 'Parallel Lives', 'Science Fiction', 21),
                                                    (18, 'The Crimson Blade', 'Fantasy', 17),
                                                    (19, 'Broken Promises', 'Romance', 18),
                                                    (20, 'Rise of the North', 'Historical Fiction', 19),

                                                    (21, 'The Last Lighthouse', 'Fiction', 20),
                                                    (22, 'The Digital Mind', 'Technology', 33),
                                                    (23, 'Letters Never Sent', 'Literary Fiction', 24),
                                                    (24, 'Valley of Kings', 'Historical Fiction', 23),
                                                    (25, 'Painted Skies', 'Drama', 44),

                                                    (26, 'The Longest Night', 'Thriller', 6),
                                                    (27, 'Quantum Echo', 'Science Fiction', 26),
                                                    (28, 'Under Silent Stars', 'Mystery', 31),
                                                    (29, 'The Last Healer', 'Fantasy', 25),
                                                    (30, 'City of Glass', 'Dystopian', 35),

                                                    (31, 'Dust and Bone', 'Crime', 17),
                                                    (32, 'The Final Accord', 'Political Thriller', 11),
                                                    (33, 'Children of Light', 'Inspirational', 18),
                                                    (34, 'Code Red', 'Tech Thriller', 51),
                                                    (35, 'The Lost Orchard', 'Cozy Fiction', 32),

                                                    (36, 'The Rising Tide', 'Adventure', 47),
                                                    (37, 'Silent Footsteps', 'Psychological Thriller', 37),
                                                    (38, 'The Paper Crown', 'Literary Fiction', 40),
                                                    (39, 'Solar Winds', 'Science Fiction', 38),
                                                    (40, 'The Broken City', 'Dystopian', 35),

                                                    (41, 'The Glass Violin', 'Drama', 44),
                                                    (42, 'The Wild Frontier', 'Adventure', 7),
                                                    (43, 'Notes from Nowhere', 'Creative Non-Fiction', 38),
                                                    (44, 'Kingdoms Apart', 'Fantasy', 39),
                                                    (45, 'The Last Signal', 'Tech Thriller', 51),

                                                    (46, 'Sea of Lanterns', 'Romance', 60),
                                                    (47, 'Runes of Power', 'Fantasy', 46),
                                                    (48, 'The Old Map', 'Adventure', 47),
                                                    (49, 'The Vanishing Point', 'Science Fiction', 48),
                                                    (50, 'Desert Bloom', 'Historical Fiction', 48),

                                                    (51, 'Oasis Dreams', 'Romance', 60),
                                                    (52, 'The Final Chapter', 'Fiction', 20),
                                                    (53, 'Machine Dreams', 'Science Fiction', 21),
                                                    (54, 'Ink and Silence', 'Literary Fiction', 24),
                                                    (55, 'Throne of Stone', 'Fantasy', 39),

                                                    (56, 'Colors of Dawn', 'Drama', 16),
                                                    (57, 'Before the Sunrise', 'Romance', 34),
                                                    (58, 'The Time Paradox', 'Science Fiction', 26),
                                                    (59, 'The Night Watcher', 'Mystery', 31),
                                                    (60, 'Herbal Moon', 'Fantasy', 28),

                                                    (61, 'Reflections', 'Literary Fiction', 40),
                                                    (62, 'The Hollow Road', 'Crime', 41),
                                                    (63, 'Treaty of Shadows', 'Political Thriller', 11),
                                                    (64, 'The Silver Dawn', 'Inspirational', 18),
                                                    (65, 'System Failure', 'Technology', 33),

                                                    (66, 'Apples of Gold', 'Cozy Fiction', 32),
                                                    (67, 'Beneath the Waves', 'Adventure', 15),
                                                    (68, 'Echo in the Dark', 'Psychological Thriller', 37),
                                                    (69, 'Inkbound', 'Literary Fiction', 24),
                                                    (70, 'Orbit of Fate', 'Science Fiction', 38),

                                                    (71, 'Ashfall', 'Dystopian', 35),
                                                    (72, 'Symphony of Silence', 'Drama', 44),
                                                    (73, 'Beyond the Rails', 'Adventure', 47),
                                                    (74, 'The Quiet Room', 'Creative Non-Fiction', 38),
                                                    (75, 'The Fractured Throne', 'Fantasy', 43),

                                                    (76, 'Dead Air', 'Tech Thriller', 51),
                                                    (77, 'Harbor Lights', 'Romance', 60),
                                                    (78, 'The Arcane Code', 'Fantasy', 46),
                                                    (79, 'Paths Unknown', 'Adventure', 7),
                                                    (80, 'Edge of Reality', 'Science Fiction', 48),

                                                    (81, 'Oath of Steel', 'Fantasy', 17),
                                                    (82, 'Shattered Dreams', 'Romance', 18),
                                                    (83, 'Stormbound', 'Adventure', 19),
                                                    (84, 'Beacon of Hope', 'Inspirational', 18),
                                                    (85, 'The Hidden Frequency', 'Thriller', 11),

                                                    (86, 'When We Were Young', 'Young Adult', 30),
                                                    (87, 'Crown of Ashes', 'Fantasy', 9),
                                                    (88, 'Moonlight Serenade', 'Romance', 10),
                                                    (89, 'Legacy of Fire', 'Fantasy', 17),
                                                    (90, 'Crossing the Divide', 'Drama', 16),

                                                    (91, 'Oathbreaker', 'Fantasy', 25),
                                                    (92, 'Frozen Skies', 'Adventure', 14),
                                                    (93, 'The Long Silence', 'Mystery', 31),
                                                    (94, 'Glass Horizons', 'Science Fiction', 21),
                                                    (95, 'Paper Dreams', 'Literary Fiction', 40),

                                                    (96, 'Runaway Signals', 'Tech Thriller', 51),
                                                    (97, 'The Golden Dunes', 'Historical Fiction', 14),
                                                    (98, 'Midnight Harbor', 'Romance', 60),
                                                    (99, 'Last Ember', 'Fantasy', 39),
                                                    (100, 'Tomorrow’s Promise', 'Inspirational', 18);